spring:
  profiles:
    active: dev
logging:
  config: classpath:logback-spring.xml

aliyun:
  log:
    endpoint: cn-beijing.log.aliyuncs.com
    accessKeyId: LTAIlsXoPNvGYZ9M
    accessKey: JZVefZj1LfBklT0ZexC3hx8zDKnzJX
    projectName: lay-project1
    logstore: lay-logstore1
    traceLogstore: lay-trace-logstore1
