server:
  port: 9003
spring:
  application:
    name: sso-server
  redis:
    database: 13
    host: 192.168.3.189
    port: 6379
    password: 123456
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
